# Generated by Django 4.0.3 on 2022-03-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('BOOK', 'Book'), ('SONG', 'Song')], default='SONG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.IntegerField()),
                ('stamp_type', models.CharField(choices=[('BOOKMARK', 'Bookmark'), ('FAVORITE', 'Favorite'), ('MEMO', 'Memo'), ('TOC', 'Toc'), ('MARKER', 'Marker')], default='MARKER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestamp.audio')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestamp.timestamp')),
            ],
        ),
    ]
