# Generated by Django 4.0.3 on 2022-03-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestamp.timestamp')),
            ],
        ),
    ]
