# Generated by Django 4.0.3 on 2022-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0002_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='second',
            field=models.FloatField(),
        ),
    ]
