# Generated by Django 4.0.3 on 2022-03-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0003_alter_timestamp_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_lyrics', models.TextField()),
                ('draft', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestamp.audio')),
            ],
        ),
    ]
