# Generated by Django 4.0.3 on 2022-04-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0004_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
